# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11aV51KO_DQeRd_9N-_V1lVTnmAj9yF16
"""

def media(lista):
  suma = sum(lista)
  media = suma/len(lista)
  return media 

def porcentaje(valor, per):
  return (valor*per)/100

def cambiopestaeuro(euros):
  return euros*166.386

def farenacels(grados):
  return ((grados-32)*5)/9

def metroscuadrados(altura,anchura):
  return altura*anchura

def metroscubicos(alt, anch, prof):
  return alt*anch*prof